// One conversation, whether the user talks to an agent in Crew or in a terminal: Crew's turns are
// already in its chat; this finds the turns they had in the terminal (`claude --resume`, Open in
// terminal) in the session's transcript, so Crew shows those too. Pure.
//
// Claude Code marks prompts that came through `claude -p` (Crew's runs) with
// promptSource "sdk"; anything else is the user at a keyboard.

/** The text of a user or assistant message, or "" if it has none (tool calls, results). */
function textOf(message) {
  const c = message?.content;
  if (typeof c === "string") return c;
  if (!Array.isArray(c)) return "";
  return c
    .filter((b) => b?.type === "text" && b.text)
    .map((b) => b.text)
    .join("\n\n");
}

/** Prompts Claude Code writes itself (slash commands, reminders), not the user's words. */
const isNoise = (text) =>
  /^\s*<(command-|local-command|system-reminder|user-memory-input)/.test(text) ||
  /^\s*Caveat: The messages below were generated by the user while running local commands/.test(
    text,
  );

/**
 * The terminal turns in transcript entries (one parsed JSON object per line).
 * @param {Array<Record<string, any>>} entries
 * @returns {Array<{ role: "you" | "agent", text: string, at: number }>}
 */
export function terminalTurns(entries) {
  const out = [];
  let fromTerminal = false;
  let reply = [];
  let replyAt = 0;
  const flush = () => {
    if (reply.length) out.push({ role: "agent", text: reply.join("\n\n").trim(), at: replyAt });
    reply = [];
  };
  for (const e of entries) {
    if (e?.type === "user" && !e.isMeta && !e.isSidechain) {
      const text = textOf(e.message).trim();
      if (!text || isNoise(text)) continue; // a tool result, or Claude Code's own
      flush();
      fromTerminal = e.promptSource !== "sdk";
      if (fromTerminal) out.push({ role: "you", text, at: Date.parse(e.timestamp) || 0 });
    } else if (e?.type === "assistant" && fromTerminal && !e.isSidechain) {
      const text = textOf(e.message).trim();
      if (text) {
        reply.push(text);
        replyAt = Date.parse(e.timestamp) || replyAt;
      }
    }
  }
  flush();
  return out;
}
